# coding: utf-8

# flake8: noqa

"""
    Vehicle Booking API by e.GO Digital 

    Describes all backend endpoints.  # noqa: E501

    OpenAPI spec version: 2.0.5
    Contact: hello@e-go-digital.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from .api.admin_api import AdminApi
from .api.bookings_api import BookingsApi
from .api.defaults_api import DefaultsApi
from .api.environments_api import EnvironmentsApi
from .api.vehicles_api import VehiclesApi

# import ApiClient
from .api_client import ApiClient
from .configuration import Configuration
# import models into sdk package
from .models.cancel_vehicle_booking_response import CancelVehicleBookingResponse
from .models.create_team_request import CreateTeamRequest
from .models.create_team_response import CreateTeamResponse
from .models.create_vehicle_booking_request import CreateVehicleBookingRequest
from .models.create_vehicle_booking_response import CreateVehicleBookingResponse
from .models.create_vehicle_request import CreateVehicleRequest
from .models.create_vehicle_response import CreateVehicleResponse
from .models.delete_vehicle_booking_response import DeleteVehicleBookingResponse
from .models.delete_vehicle_response import DeleteVehicleResponse
from .models.environment_item import EnvironmentItem
from .models.environment_list_response import EnvironmentListResponse
from .models.error_response import ErrorResponse
from .models.finish_vehicle_booking_response import FinishVehicleBookingResponse
from .models.general_info_response import GeneralInfoResponse
from .models.general_info_response_data import GeneralInfoResponseData
from .models.general_info_response_data_me import GeneralInfoResponseDataMe
from .models.get_vehicle_response import GetVehicleResponse
from .models.list_teams_response import ListTeamsResponse
from .models.on_off_status import OnOffStatus
from .models.open_status import OpenStatus
from .models.start_vehicle_booking_response import StartVehicleBookingResponse
from .models.team_item import TeamItem
from .models.team_item_with_api_key import TeamItemWithApiKey
from .models.update_vehicle_request import UpdateVehicleRequest
from .models.update_vehicle_response import UpdateVehicleResponse
from .models.vehicle_booking_item import VehicleBookingItem
from .models.vehicle_booking_list_response import VehicleBookingListResponse
from .models.vehicle_event_item import VehicleEventItem
from .models.vehicle_event_list_response import VehicleEventListResponse
from .models.vehicle_item import VehicleItem
from .models.vehicle_list_response import VehicleListResponse
from .models.vehicle_signal_item import VehicleSignalItem
from .models.vehicle_signal_list_for_patch_example import VehicleSignalListForPatchExample
from .models.vehicle_signal_list_response import VehicleSignalListResponse
from .models.vehicle_signal_list_response_data import VehicleSignalListResponseData
from .models.vehicle_signal_log_item import VehicleSignalLogItem
from .models.vehicle_signal_log_list_response import VehicleSignalLogListResponse
from .models.yes_or_no import YesOrNo
