# coding: utf-8

"""
    Vehicle Booking API by e.GO Digital 

    Describes all backend endpoints.  # noqa: E501

    OpenAPI spec version: 2.0.5
    Contact: hello@e-go-digital.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.vehicles_api import VehiclesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestVehiclesApi(unittest.TestCase):
    """VehiclesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.vehicles_api.VehiclesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v2_vehicles_get(self):
        """Test case for api_v2_vehicles_get

        Returns a list of all vehicles.  # noqa: E501
        """
        pass

    def test_api_v2_vehicles_post(self):
        """Test case for api_v2_vehicles_post

        Creates a new vehicle.  # noqa: E501
        """
        pass

    def test_api_v2_vehicles_vehicle_id_bookings_get(self):
        """Test case for api_v2_vehicles_vehicle_id_bookings_get

        Returns a list of bookings of a vehicle, with optional filters.  # noqa: E501
        """
        pass

    def test_api_v2_vehicles_vehicle_id_bookings_post(self):
        """Test case for api_v2_vehicles_vehicle_id_bookings_post

        Creates a new booking for a vehicle.  # noqa: E501
        """
        pass

    def test_api_v2_vehicles_vehicle_id_delete(self):
        """Test case for api_v2_vehicles_vehicle_id_delete

        Resets the complete vehicle.  # noqa: E501
        """
        pass

    def test_api_v2_vehicles_vehicle_id_events_delete(self):
        """Test case for api_v2_vehicles_vehicle_id_events_delete

        Removes the complete queue of events.  # noqa: E501
        """
        pass

    def test_api_v2_vehicles_vehicle_id_events_get(self):
        """Test case for api_v2_vehicles_vehicle_id_events_get

        Gets a list of unhandled events and marks them as handled.  # noqa: E501
        """
        pass

    def test_api_v2_vehicles_vehicle_id_get(self):
        """Test case for api_v2_vehicles_vehicle_id_get

        Returns the information of the vehicle.  # noqa: E501
        """
        pass

    def test_api_v2_vehicles_vehicle_id_infotainment_delete(self):
        """Test case for api_v2_vehicles_vehicle_id_infotainment_delete

        Resets the infotainment screen.  # noqa: E501
        """
        pass

    def test_api_v2_vehicles_vehicle_id_infotainment_get(self):
        """Test case for api_v2_vehicles_vehicle_id_infotainment_get

        Gets the current infotainment screen.  # noqa: E501
        """
        pass

    def test_api_v2_vehicles_vehicle_id_infotainment_post(self):
        """Test case for api_v2_vehicles_vehicle_id_infotainment_post

        Sets the data of the screen as image or video.  # noqa: E501
        """
        pass

    def test_api_v2_vehicles_vehicle_id_infotainment_put(self):
        """Test case for api_v2_vehicles_vehicle_id_infotainment_put

        Writes an image to the infotainment screen.  # noqa: E501
        """
        pass

    def test_api_v2_vehicles_vehicle_id_infotainment_text_put(self):
        """Test case for api_v2_vehicles_vehicle_id_infotainment_text_put

        Writes text to the infotainment system.  # noqa: E501
        """
        pass

    def test_api_v2_vehicles_vehicle_id_logs_signals_delete(self):
        """Test case for api_v2_vehicles_vehicle_id_logs_signals_delete

        Deletes all vehicle signal logs.  # noqa: E501
        """
        pass

    def test_api_v2_vehicles_vehicle_id_logs_signals_get(self):
        """Test case for api_v2_vehicles_vehicle_id_logs_signals_get

        Gets vehicle signal logs.  # noqa: E501
        """
        pass

    def test_api_v2_vehicles_vehicle_id_patch(self):
        """Test case for api_v2_vehicles_vehicle_id_patch

        Updates a vehicle.  # noqa: E501
        """
        pass

    def test_api_v2_vehicles_vehicle_id_signals_delete(self):
        """Test case for api_v2_vehicles_vehicle_id_signals_delete

        Resets all signals.  # noqa: E501
        """
        pass

    def test_api_v2_vehicles_vehicle_id_signals_get(self):
        """Test case for api_v2_vehicles_vehicle_id_signals_get

        Gets a list of all signals.  # noqa: E501
        """
        pass

    def test_api_v2_vehicles_vehicle_id_signals_patch(self):
        """Test case for api_v2_vehicles_vehicle_id_signals_patch

        Updates a list of one or more vehicle signals.  # noqa: E501
        """
        pass

    def test_api_v2_vehicles_vehicle_id_state_delete(self):
        """Test case for api_v2_vehicles_vehicle_id_state_delete

        Unsets the state value for the vehicle.  # noqa: E501
        """
        pass

    def test_api_v2_vehicles_vehicle_id_state_get(self):
        """Test case for api_v2_vehicles_vehicle_id_state_get

        Gets the state value of the vehicle.  # noqa: E501
        """
        pass

    def test_api_v2_vehicles_vehicle_id_state_patch(self):
        """Test case for api_v2_vehicles_vehicle_id_state_patch

        Sets a state value for the vehicle.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
