# coding: utf-8

"""
    Vehicle Booking API by e.GO Digital 

    Describes all backend endpoints.  # noqa: E501

    OpenAPI spec version: 2.0.5
    Contact: hello@e-go-digital.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.environments_api import EnvironmentsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEnvironmentsApi(unittest.TestCase):
    """EnvironmentsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.environments_api.EnvironmentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v2_environments_environment_id_vehicles_get(self):
        """Test case for api_v2_environments_environment_id_vehicles_get

        Returns a list of all vehicles of an environment.  # noqa: E501
        """
        pass

    def test_api_v2_environments_get(self):
        """Test case for api_v2_environments_get

        Returns a list of all environments.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
