# coding: utf-8

"""
    Vehicle Booking API by e.GO Digital 

    Describes all backend endpoints.  # noqa: E501

    OpenAPI spec version: 2.0.5
    Contact: hello@e-go-digital.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.admin_api import AdminApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.admin_api.AdminApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_teams_get(self):
        """Test case for admin_teams_get

        Lists all teams.  # noqa: E501
        """
        pass

    def test_admin_teams_post(self):
        """Test case for admin_teams_post

        Creates a new team.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
