# coding: utf-8

"""
    Vehicle Booking API by e.GO Digital 

    Describes all backend endpoints.  # noqa: E501

    OpenAPI spec version: 2.0.5
    Contact: hello@e-go-digital.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.delete_vehicle_booking_response import DeleteVehicleBookingResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestDeleteVehicleBookingResponse(unittest.TestCase):
    """DeleteVehicleBookingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteVehicleBookingResponse(self):
        """Test DeleteVehicleBookingResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.delete_vehicle_booking_response.DeleteVehicleBookingResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
