# coding: utf-8

"""
    Vehicle Booking API by e.GO Digital 

    Describes all backend endpoints.  # noqa: E501

    OpenAPI spec version: 2.0.5
    Contact: hello@e-go-digital.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.defaults_api import DefaultsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultsApi(unittest.TestCase):
    """DefaultsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.defaults_api.DefaultsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v2_delete(self):
        """Test case for api_v2_delete

        Resets the data of the current team.  # noqa: E501
        """
        pass

    def test_api_v2_get(self):
        """Test case for api_v2_get

        Returns general information.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
