# coding: utf-8

"""
    Vehicle Booking API by e.GO Digital 

    Describes all backend endpoints.  # noqa: E501

    OpenAPI spec version: 2.0.5
    Contact: hello@e-go-digital.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.bookings_api import BookingsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBookingsApi(unittest.TestCase):
    """BookingsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.bookings_api.BookingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v2_bookings_booking_id_cancel_patch(self):
        """Test case for api_v2_bookings_booking_id_cancel_patch

        Cancels a booking.  # noqa: E501
        """
        pass

    def test_api_v2_bookings_booking_id_delete(self):
        """Test case for api_v2_bookings_booking_id_delete

        Deletes a vehicle booking.  # noqa: E501
        """
        pass

    def test_api_v2_bookings_booking_id_finish_patch(self):
        """Test case for api_v2_bookings_booking_id_finish_patch

        Finishes a booking.  # noqa: E501
        """
        pass

    def test_api_v2_bookings_booking_id_start_patch(self):
        """Test case for api_v2_bookings_booking_id_start_patch

        Starts a booking.  # noqa: E501
        """
        pass

    def test_api_v2_bookings_get(self):
        """Test case for api_v2_bookings_get

        Returns all vehicle bookings.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
