# coding: utf-8

# flake8: noqa
"""
    Vehicle Booking API by e.GO Digital 

    Describes all backend endpoints.  # noqa: E501

    OpenAPI spec version: 2.0.5
    Contact: hello@e-go-digital.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .cancel_vehicle_booking_response import CancelVehicleBookingResponse
from .create_team_request import CreateTeamRequest
from .create_team_response import CreateTeamResponse
from .create_vehicle_booking_request import CreateVehicleBookingRequest
from .create_vehicle_booking_response import CreateVehicleBookingResponse
from .create_vehicle_request import CreateVehicleRequest
from .create_vehicle_response import CreateVehicleResponse
from .delete_vehicle_booking_response import DeleteVehicleBookingResponse
from .delete_vehicle_response import DeleteVehicleResponse
from .environment_item import EnvironmentItem
from .environment_list_response import EnvironmentListResponse
from .error_response import ErrorResponse
from .finish_vehicle_booking_response import FinishVehicleBookingResponse
from .general_info_response import GeneralInfoResponse
from .general_info_response_data import GeneralInfoResponseData
from .general_info_response_data_me import GeneralInfoResponseDataMe
from .get_vehicle_response import GetVehicleResponse
from .list_teams_response import ListTeamsResponse
from .on_off_status import OnOffStatus
from .open_status import OpenStatus
from .start_vehicle_booking_response import StartVehicleBookingResponse
from .team_item import TeamItem
from .team_item_with_api_key import TeamItemWithApiKey
from .update_vehicle_request import UpdateVehicleRequest
from .update_vehicle_response import UpdateVehicleResponse
from .vehicle_booking_item import VehicleBookingItem
from .vehicle_booking_list_response import VehicleBookingListResponse
from .vehicle_event_item import VehicleEventItem
from .vehicle_event_list_response import VehicleEventListResponse
from .vehicle_item import VehicleItem
from .vehicle_list_response import VehicleListResponse
from .vehicle_signal_item import VehicleSignalItem
from .vehicle_signal_list_for_patch_example import VehicleSignalListForPatchExample
from .vehicle_signal_list_response import VehicleSignalListResponse
from .vehicle_signal_list_response_data import VehicleSignalListResponseData
from .vehicle_signal_log_item import VehicleSignalLogItem
from .vehicle_signal_log_list_response import VehicleSignalLogListResponse
from .yes_or_no import YesOrNo
