# coding: utf-8

"""
    Vehicle Booking API by e.GO Digital 

    Describes all backend endpoints.  # noqa: E501

    OpenAPI spec version: 2.0.5
    Contact: hello@e-go-digital.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CreateVehicleRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'country': 'str',
        'license_plate': 'str',
        'manufacturer': 'str',
        'model': 'str',
        'name': 'str'
    }

    attribute_map = {
        'country': 'country',
        'license_plate': 'licensePlate',
        'manufacturer': 'manufacturer',
        'model': 'model',
        'name': 'name'
    }

    def __init__(self, country=None, license_plate=None, manufacturer=None, model=None, name=None):  # noqa: E501
        """CreateVehicleRequest - a model defined in Swagger"""  # noqa: E501

        self._country = None
        self._license_plate = None
        self._manufacturer = None
        self._model = None
        self._name = None
        self.discriminator = None

        if country is not None:
            self.country = country
        self.license_plate = license_plate
        self.manufacturer = manufacturer
        self.model = model
        if name is not None:
            self.name = name

    @property
    def country(self):
        """Gets the country of this CreateVehicleRequest.  # noqa: E501

        The country (code).  # noqa: E501

        :return: The country of this CreateVehicleRequest.  # noqa: E501
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this CreateVehicleRequest.

        The country (code).  # noqa: E501

        :param country: The country of this CreateVehicleRequest.  # noqa: E501
        :type: str
        """

        self._country = country

    @property
    def license_plate(self):
        """Gets the license_plate of this CreateVehicleRequest.  # noqa: E501

        The license plate.  # noqa: E501

        :return: The license_plate of this CreateVehicleRequest.  # noqa: E501
        :rtype: str
        """
        return self._license_plate

    @license_plate.setter
    def license_plate(self, license_plate):
        """Sets the license_plate of this CreateVehicleRequest.

        The license plate.  # noqa: E501

        :param license_plate: The license_plate of this CreateVehicleRequest.  # noqa: E501
        :type: str
        """
        if license_plate is None:
            raise ValueError("Invalid value for `license_plate`, must not be `None`")  # noqa: E501

        self._license_plate = license_plate

    @property
    def manufacturer(self):
        """Gets the manufacturer of this CreateVehicleRequest.  # noqa: E501

        The manufacturer.  # noqa: E501

        :return: The manufacturer of this CreateVehicleRequest.  # noqa: E501
        :rtype: str
        """
        return self._manufacturer

    @manufacturer.setter
    def manufacturer(self, manufacturer):
        """Sets the manufacturer of this CreateVehicleRequest.

        The manufacturer.  # noqa: E501

        :param manufacturer: The manufacturer of this CreateVehicleRequest.  # noqa: E501
        :type: str
        """
        if manufacturer is None:
            raise ValueError("Invalid value for `manufacturer`, must not be `None`")  # noqa: E501

        self._manufacturer = manufacturer

    @property
    def model(self):
        """Gets the model of this CreateVehicleRequest.  # noqa: E501

        The model.  # noqa: E501

        :return: The model of this CreateVehicleRequest.  # noqa: E501
        :rtype: str
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this CreateVehicleRequest.

        The model.  # noqa: E501

        :param model: The model of this CreateVehicleRequest.  # noqa: E501
        :type: str
        """
        if model is None:
            raise ValueError("Invalid value for `model`, must not be `None`")  # noqa: E501

        self._model = model

    @property
    def name(self):
        """Gets the name of this CreateVehicleRequest.  # noqa: E501

        The name.  # noqa: E501

        :return: The name of this CreateVehicleRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateVehicleRequest.

        The name.  # noqa: E501

        :param name: The name of this CreateVehicleRequest.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateVehicleRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateVehicleRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
