# coding: utf-8

"""
    Vehicle Booking API by e.GO Digital 

    Describes all backend endpoints.  # noqa: E501

    OpenAPI spec version: 2.0.5
    Contact: hello@e-go-digital.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class EnvironmentItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'team': 'TeamItem'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'team': 'team'
    }

    def __init__(self, id=None, name=None, team=None):  # noqa: E501
        """EnvironmentItem - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._team = None
        self.discriminator = None

        self.id = id
        self.name = name
        if team is not None:
            self.team = team

    @property
    def id(self):
        """Gets the id of this EnvironmentItem.  # noqa: E501

        The ID of the environment.  # noqa: E501

        :return: The id of this EnvironmentItem.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EnvironmentItem.

        The ID of the environment.  # noqa: E501

        :param id: The id of this EnvironmentItem.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this EnvironmentItem.  # noqa: E501

        The name of the environment.  # noqa: E501

        :return: The name of this EnvironmentItem.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EnvironmentItem.

        The name of the environment.  # noqa: E501

        :param name: The name of this EnvironmentItem.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def team(self):
        """Gets the team of this EnvironmentItem.  # noqa: E501

        The underlying team.  # noqa: E501

        :return: The team of this EnvironmentItem.  # noqa: E501
        :rtype: TeamItem
        """
        return self._team

    @team.setter
    def team(self, team):
        """Sets the team of this EnvironmentItem.

        The underlying team.  # noqa: E501

        :param team: The team of this EnvironmentItem.  # noqa: E501
        :type: TeamItem
        """

        self._team = team

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EnvironmentItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EnvironmentItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
