# coding: utf-8

"""
    Vehicle Booking API by e.GO Digital 

    Describes all backend endpoints.  # noqa: E501

    OpenAPI spec version: 2.0.5
    Contact: hello@e-go-digital.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class TeamItemWithApiKey(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'api_key': 'str',
        'id': 'str',
        'name': 'str'
    }

    attribute_map = {
        'api_key': 'apiKey',
        'id': 'id',
        'name': 'name'
    }

    def __init__(self, api_key=None, id=None, name=None):  # noqa: E501
        """TeamItemWithApiKey - a model defined in Swagger"""  # noqa: E501

        self._api_key = None
        self._id = None
        self._name = None
        self.discriminator = None

        self.api_key = api_key
        self.id = id
        self.name = name

    @property
    def api_key(self):
        """Gets the api_key of this TeamItemWithApiKey.  # noqa: E501

        The API key of the team.  # noqa: E501

        :return: The api_key of this TeamItemWithApiKey.  # noqa: E501
        :rtype: str
        """
        return self._api_key

    @api_key.setter
    def api_key(self, api_key):
        """Sets the api_key of this TeamItemWithApiKey.

        The API key of the team.  # noqa: E501

        :param api_key: The api_key of this TeamItemWithApiKey.  # noqa: E501
        :type: str
        """
        if api_key is None:
            raise ValueError("Invalid value for `api_key`, must not be `None`")  # noqa: E501

        self._api_key = api_key

    @property
    def id(self):
        """Gets the id of this TeamItemWithApiKey.  # noqa: E501

        The ID of the team.  # noqa: E501

        :return: The id of this TeamItemWithApiKey.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TeamItemWithApiKey.

        The ID of the team.  # noqa: E501

        :param id: The id of this TeamItemWithApiKey.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this TeamItemWithApiKey.  # noqa: E501

        The name of the team.  # noqa: E501

        :return: The name of this TeamItemWithApiKey.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TeamItemWithApiKey.

        The name of the team.  # noqa: E501

        :param name: The name of this TeamItemWithApiKey.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TeamItemWithApiKey, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TeamItemWithApiKey):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
