# coding: utf-8

"""
    Vehicle Booking API by e.GO Digital 

    Describes all backend endpoints.  # noqa: E501

    OpenAPI spec version: 2.0.5
    Contact: hello@e-go-digital.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CreateVehicleBookingRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_from': 'str',
        'until': 'str'
    }

    attribute_map = {
        '_from': 'from',
        'until': 'until'
    }

    def __init__(self, _from=None, until=None):  # noqa: E501
        """CreateVehicleBookingRequest - a model defined in Swagger"""  # noqa: E501

        self.__from = None
        self._until = None
        self.discriminator = None

        self._from = _from
        self.until = until

    @property
    def _from(self):
        """Gets the _from of this CreateVehicleBookingRequest.  # noqa: E501

        The start date.  # noqa: E501

        :return: The _from of this CreateVehicleBookingRequest.  # noqa: E501
        :rtype: str
        """
        return self.__from

    @_from.setter
    def _from(self, _from):
        """Sets the _from of this CreateVehicleBookingRequest.

        The start date.  # noqa: E501

        :param _from: The _from of this CreateVehicleBookingRequest.  # noqa: E501
        :type: str
        """
        if _from is None:
            raise ValueError("Invalid value for `_from`, must not be `None`")  # noqa: E501

        self.__from = _from

    @property
    def until(self):
        """Gets the until of this CreateVehicleBookingRequest.  # noqa: E501

        The end date.  # noqa: E501

        :return: The until of this CreateVehicleBookingRequest.  # noqa: E501
        :rtype: str
        """
        return self._until

    @until.setter
    def until(self, until):
        """Sets the until of this CreateVehicleBookingRequest.

        The end date.  # noqa: E501

        :param until: The until of this CreateVehicleBookingRequest.  # noqa: E501
        :type: str
        """
        if until is None:
            raise ValueError("Invalid value for `until`, must not be `None`")  # noqa: E501

        self._until = until

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateVehicleBookingRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateVehicleBookingRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
